target_variable: unemployment_unemployment_total

train_test_split_ratio: 0.8

random_state: 42

model:
  model_type: lightgbm
  param_grid:
    n_estimators: [10, 20, 50, 100]
    max_depth: [2, 3, 5]
    num_leaves: [10, 20, 31]
