target_variable: unemployment_unemployment_per_capita

feature_filtering:
  omit_features: [
    "unemployment_unemployment_total",
    "unemployment_ausl√§ndisch",
    "unemployment_schwerbehindert",
    "unemployment_15 bis unter 20 Jahre",
    "unemployment_15 bis unter 25 Jahre",
    "unemployment_55 bis unter 65 Jahre",
    "unemployment_langzeitarbeitslos"
  ]

train_test_split_ratio: 0.8

random_state: 42

model:
  model_type: lightgbm
  param_grid:
    n_estimators: [10, 20, 50, 100]
    max_depth: [2, 3, 5]
    num_leaves: [10, 20, 31]
